/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DbUsuarios;
import Modelo.DbUsuariosConsulta;
import Modelo.hash;
import javax.swing.JOptionPane;




public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        FondoLogin = new javax.swing.JPanel();
        UsuLog = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PwdLog = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnEntLog = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        FondoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuLog.setBackground(new java.awt.Color(255, 255, 255));
        UsuLog.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UsuLog.setForeground(new java.awt.Color(0, 0, 0));
        FondoLogin.add(UsuLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 180, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuario:");
        FondoLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, 20));

        PwdLog.setBackground(new java.awt.Color(255, 255, 255));
        PwdLog.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PwdLog.setForeground(new java.awt.Color(0, 0, 0));
        FondoLogin.add(PwdLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 180, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña:");
        FondoLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        btnEntLog.setBackground(new java.awt.Color(255, 255, 255));
        btnEntLog.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnEntLog.setForeground(new java.awt.Color(0, 0, 0));
        btnEntLog.setText("Iniciar");
        btnEntLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntLogActionPerformed(evt);
            }
        });
        FondoLogin.add(btnEntLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 90, 30));

        Salir.setBackground(new java.awt.Color(255, 255, 255));
        Salir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        FondoLogin.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 90, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/640-pastillas-de-medicina-sobre-fondo-azul.jpg"))); // NOI18N
        FondoLogin.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 640, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntLogActionPerformed
        // TODO add your handling code here:
        
         DbUsuarios objx = new DbUsuarios();
         DbUsuariosConsulta objy = new DbUsuariosConsulta();
         
         String pass = new String(PwdLog.getPassword());
         
         if(!UsuLog.getText().equals("") && !pass.equals("") ){
             
             String NuevoPass = hash.sha1(pass);
            objx.setUsuario(UsuLog.getText());
            objx.setPassword(NuevoPass);
            
            if(objy.Login(objx)){
                
        
           Inicio obj = new Inicio();
           obj.setVisible(true);
           dispose();
                
                
            }else{
                JOptionPane.showMessageDialog(null, "los datos son incorrectos");
            }
             
         }else{
            JOptionPane.showMessageDialog(null, "los datos estan vacios");
        }
 
          
    }//GEN-LAST:event_btnEntLogActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel FondoLogin;
    private javax.swing.JPasswordField PwdLog;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField UsuLog;
    private javax.swing.JButton btnEntLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
