/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.DbConexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class Turno extends javax.swing.JFrame {

PreparedStatement ps;
ResultSet Res;


    
    
    
    /**
     * Creates new form Paciente
     */
    public Turno() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PacNom = new javax.swing.JTextField();
        MedNom = new javax.swing.JTextField();
        MedEsp = new javax.swing.JTextField();
        FechTur = new javax.swing.JTextField();
        HorTur = new javax.swing.JTextField();
        MonCon = new javax.swing.JTextField();
        CodTur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NumTur = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        LisTur = new javax.swing.JTable();
        GuaTur = new javax.swing.JButton();
        BusTur = new javax.swing.JButton();
        IdTurno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 57, -1));

        PacNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacNomActionPerformed(evt);
            }
        });
        jPanel1.add(PacNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 30));

        MedNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedNomActionPerformed(evt);
            }
        });
        jPanel1.add(MedNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 30));

        MedEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedEspActionPerformed(evt);
            }
        });
        jPanel1.add(MedEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 30));

        FechTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechTurActionPerformed(evt);
            }
        });
        jPanel1.add(FechTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 150, 30));

        HorTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorTurActionPerformed(evt);
            }
        });
        jPanel1.add(HorTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, 30));

        MonCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonConActionPerformed(evt);
            }
        });
        jPanel1.add(MonCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 150, 30));

        CodTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodTurActionPerformed(evt);
            }
        });
        jPanel1.add(CodTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo del Turno");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Turno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 90, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Médico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Especialidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 80, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 50, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Monto Consulta:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 100, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Hora:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 50, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Número Turrno:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 20));

        NumTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTurActionPerformed(evt);
            }
        });
        jPanel1.add(NumTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 30));

        LisTur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TUR01", "01", "Josefa", "Cyndi", "Pediatra", "9:00AM", "Lunes"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Numero", "Paciente", "Medico", "Especialidad", "Hora", "Dia"
            }
        ));
        jScrollPane1.setViewportView(LisTur);
        if (LisTur.getColumnModel().getColumnCount() > 0) {
            LisTur.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 540, 130));

        GuaTur.setText("Guardar");
        GuaTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuaTurActionPerformed(evt);
            }
        });
        jPanel1.add(GuaTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 130, 60));

        BusTur.setText("Buscar");
        BusTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusTurActionPerformed(evt);
            }
        });
        jPanel1.add(BusTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 150, 60));

        IdTurno.setEditable(false);
        jPanel1.add(IdTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 60, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Paciente:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Inicio obj = new Inicio();
           obj.setVisible(true);
           dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PacNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacNomActionPerformed

    private void MedNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedNomActionPerformed

    private void MedEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedEspActionPerformed

    private void FechTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechTurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechTurActionPerformed

    private void HorTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorTurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorTurActionPerformed

    private void MonConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonConActionPerformed

    private void CodTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodTurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodTurActionPerformed

    private void NumTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTurActionPerformed

    private void GuaTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuaTurActionPerformed
        // TODO add your handling code here:
        
          Connection Conexion = null;
          DbConexion obj = new DbConexion();
          
        try{
            
            Conexion = obj.getConexion();
            ps = Conexion.prepareStatement("INSERT INTO Turnos(Codigo,Numero,Paciente,Medico,Especialidad,Fecha,Hora,Monto) VALUES (?,?,?,?,?,?,?,?)");
            ps.setString(1,CodTur.getText());
            ps.setString(2,NumTur.getText());
            ps.setString(3,PacNom.getText());
            ps.setString(4,MedNom.getText());
            ps.setString(5,MedEsp.getText());
            ps.setString(6,FechTur.getText());
            ps.setString(7,HorTur.getText());
            ps.setString(8,MonCon.getText());
            
            
           int res =  ps.executeUpdate();
           
           if(res>0){
               
               JOptionPane.showMessageDialog(null, "TURNO GUARDADO. ");
               //Limpiar();
               
           }else{
               JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR. ");
           }
            
            Conexion.close();
            
            
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
    }                                            

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_GuaTurActionPerformed

    private void BusTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusTurActionPerformed
        // TODO add your handling code here:
        
        Connection Conexion = null;
        DbConexion obj = new DbConexion();
        
        try{

            Conexion = obj.getConexion();

            ps = Conexion.prepareStatement("SELECT *FROM Turnos WHERE Codigo = ? OR Paciente = ? OR Numero = ?");
            ps.setString(1, CodTur.getText());
            ps.setString(2, PacNom.getText());
            ps.setString(3, NumTur.getText());
            
            Res = ps.executeQuery();

            if(Res.next()){

                IdTurno.setText(Res.getString("idTurnos"));
                CodTur.setText(Res.getString("Codigo"));
                NumTur.setText(Res.getString("Numero"));
                PacNom.setText(Res.getString("Paciente"));
                MedNom.setText(Res.getString("Medico"));
                MedEsp.setText(Res.getString("Especialidad"));
                FechTur.setText(Res.getString("Fecha"));
                HorTur.setText(Res.getString("Hora"));
                MonCon.setText(Res.getString("Monto"));
                
            }else{

                JOptionPane.showMessageDialog(null, "No existe Medico asociado a ese codigo");

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }

        
        
        
    }//GEN-LAST:event_BusTurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusTur;
    private javax.swing.JTextField CodTur;
    private javax.swing.JTextField FechTur;
    private javax.swing.JButton GuaTur;
    private javax.swing.JTextField HorTur;
    private javax.swing.JTextField IdTurno;
    private javax.swing.JTable LisTur;
    private javax.swing.JTextField MedEsp;
    private javax.swing.JTextField MedNom;
    private javax.swing.JTextField MonCon;
    private javax.swing.JTextField NumTur;
    private javax.swing.JTextField PacNom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
